# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.13','3.12','3.11']
    steps:
    - name: Echo
      run: |
        echo ${{ github.ref }}
    - uses: actions/checkout@v4
    - uses: xbabka01/poetry-action@v1
      with:
        python_version: ${{ matrix.python_version }}
    - name: Poetry check
      # Check onlt in one version of Python
      # This is useful to ensure that the lock file is up to date
      # But 
      if: matrix.python_version == '3.13'
      run: |
        poetry check --lock
    - name: Install dependencies
      run: |
         poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/pull/16/merge' || startsWith(github.ref, 'refs/tags'))
    steps:
    - uses: actions/checkout@v4
    - uses: xbabka01/poetry-action@v1
      with:
        python_version: '3.13'
    - name: Build package
      run: |
        poetry build
    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 1